# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicsection',
            name='id',
        ),
        migrations.AddField(
            model_name='topicsection',
            name='topic_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
