# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20171208_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicsection',
            name='topic_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
