# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20171208_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicsection',
            name='topic_id',
        ),
        migrations.AddField(
            model_name='topicsection',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
