# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20171208_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('headline', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('article_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.TopicSection')),
            ],
        ),
    ]
