# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='article-slug', max_length=140),
            preserve_default=False,
        ),
    ]
